name: CI-version

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  tests-1:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - 1.59
          - stable
          - nightly
        target:
          - x86_64-unknown-linux-gnu
        features:
          -
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} to ${{ matrix.target }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install libpcsclite-dev
        run: |
          sudo apt update
          sudo apt install libpcsclite-dev
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
      - run: cargo test --release --target ${{ matrix.target }} ${{ matrix.features }}
      - run: cargo doc --release --target ${{ matrix.target }} ${{ matrix.features }}

  tests-2:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        toolchain:
          - 1.59
          - stable
          - nightly
        features:
          -
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
      - run: cargo test --release ${{ matrix.features }}
      - run: cargo doc --release ${{ matrix.features }}