name: CI-version

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  tests-1:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - stable
          - nightly
        target:
          - x86_64-unknown-linux-gnu
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} to ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install libpcsclite-dev
        run: |
          sudo apt update
          sudo apt install libpcsclite-dev
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo build --release --target ${{ matrix.target }}
      - run: cargo test --release --target ${{ matrix.target }}
      - run: cargo doc --release --target ${{ matrix.target }}

  tests-2:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          - nightly
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - run: cargo build --release
      - run: cargo test --release
      - run: cargo doc --release