name: CI

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install libpcsclite-dev
        run: |
          sudo apt update
          sudo apt install libpcsclite-dev
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  tests-1:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - stable
          - nightly
        target:
          - x86_64-unknown-linux-gnu
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} to ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install libpcsclite-dev
        run: |
          sudo apt update
          sudo apt install libpcsclite-dev
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo build --target ${{ matrix.target }}
      - run: cargo test --target ${{ matrix.target }}
      - run: cargo doc --target ${{ matrix.target }}

  tests-2:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          - nightly
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - run: cargo build
      - run: cargo test
      - run: cargo doc